language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
keep_history: true
on:
  branch: release

notifications:
  email:
    - ru-q-ur@163.com
  on_failure: always